name: CI

on:
  workflow_dispatch:
 
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      NAME: ${{ secrets.NAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}
    strategy:
      matrix:
        app: [ emails, library, users ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up and run tests
      run: |
        python3.10 -m venv venv
        source venv/bin/activate
        cd final_project
        python -m pip install -r requirements.txt
        python manage.py test ${{ matrix.app }}
