name: CI

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ emails, library, users ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up and run tests
      run: |
        python3.10 -m venv venv
        source venv/bin/activate
        cd final_project
        python -m pip install -r requirements.txt
        python manage.py test ${{ matrix.app }}
